workspace(name = "dotnet_samples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    tag = "0.0.3",
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "e513c0ac6534810eb7a14bf025a0f159726753f97f74ab7863c650d26e01d677",
    strip_prefix = "rules_docker-0.9.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.9.0.tar.gz"],
)

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_register_sdk", "net_register_sdk", "mono_register_sdk",
    "dotnet_register_toolchains", "dotnet_repositories", "nuget_package")

dotnet_register_toolchains()
dotnet_repositories()
core_register_sdk("v2.2.101", name = "core_sdk")

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

# This is NOT needed when going through the language lang_image
# "repositories" function(s).
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
  name = "core_runtime",
  registry = "mcr.microsoft.com",
  repository = "dotnet/core/runtime",
  tag = "2.2" 
)


### Generated by the tool
nuget_package(
    name = "microsoft.diagnostics.tracing.eventsource.redist",
    package = "microsoft.diagnostics.tracing.eventsource.redist",
    version = "1.1.28",
    net_lib = {
        "net45": "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net451": "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net452": "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net46": "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net461": "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net462": "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net47": "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net471": "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "net472": "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
    },
    mono_lib = "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
    net_files = {
        "net45": [
           "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net451": [
           "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net452": [
           "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net40/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net46": [
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net461": [
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net462": [
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net47": [
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net471": [
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
        "net472": [
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
           "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
        ],
    },
    mono_files = [
        "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.dll",
        "lib/net46/Microsoft.Diagnostics.Tracing.EventSource.XML",
    ],
)
nuget_package(
    name = "rabbitmq.client",
    package = "rabbitmq.client",
    version = "5.1.0",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard1.5/RabbitMQ.Client.dll",
        "netcoreapp2.1": "lib/netstandard1.5/RabbitMQ.Client.dll",
    },
    net_lib = {
        "net451": "lib/net451/RabbitMQ.Client.dll",
        "net452": "lib/net451/RabbitMQ.Client.dll",
        "net46": "lib/net451/RabbitMQ.Client.dll",
        "net461": "lib/net451/RabbitMQ.Client.dll",
        "net462": "lib/net451/RabbitMQ.Client.dll",
        "net47": "lib/net451/RabbitMQ.Client.dll",
        "net471": "lib/net451/RabbitMQ.Client.dll",
        "net472": "lib/net451/RabbitMQ.Client.dll",
        "netstandard1.5": "lib/netstandard1.5/RabbitMQ.Client.dll",
        "netstandard1.6": "lib/netstandard1.5/RabbitMQ.Client.dll",
        "netstandard2.0": "lib/netstandard1.5/RabbitMQ.Client.dll",
    },
    mono_lib = "lib/net451/RabbitMQ.Client.dll",
    net_deps = {
        "net451": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net451_net",
        ],
        "net452": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net452_net",
        ],
        "net46": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net46_net",
        ],
        "net461": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net461_net",
        ],
        "net462": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net462_net",
        ],
        "net47": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net47_net",
        ],
        "net471": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net471_net",
        ],
        "net472": [
           "@microsoft.diagnostics.tracing.eventsource.redist//:net472_net",
        ],
    },
    mono_deps = [
        "@microsoft.diagnostics.tracing.eventsource.redist//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard1.5/RabbitMQ.Client.dll",
           "lib/netstandard1.5/RabbitMQ.Client.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard1.5/RabbitMQ.Client.dll",
           "lib/netstandard1.5/RabbitMQ.Client.xml",
        ],
    },
    net_files = {
        "net451": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net452": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net46": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net461": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net462": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net47": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net471": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "net472": [
           "lib/net451/RabbitMQ.Client.dll",
           "lib/net451/RabbitMQ.Client.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.5/RabbitMQ.Client.dll",
           "lib/netstandard1.5/RabbitMQ.Client.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.5/RabbitMQ.Client.dll",
           "lib/netstandard1.5/RabbitMQ.Client.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard1.5/RabbitMQ.Client.dll",
           "lib/netstandard1.5/RabbitMQ.Client.xml",
        ],
    },
    mono_files = [
        "lib/net451/RabbitMQ.Client.dll",
        "lib/net451/RabbitMQ.Client.xml",
    ],
)
### End of generated by the tool
